server:
  port: 5555

liquibase:
  contexts: local
  enabled: true

security:
  user:
    password: none
  oauth2:
    client:
      accessTokenUri: localhost:8901/oauth/token
      clientId: clientapp
    
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    userservice: 
      path: /user/**
      sensitiveHeaders:
    itemservice:
      path: /item/**
      sensitiveHeaders:
  ignored-service: '*'
  prefix: /api    
  
    
logging:
  level:
    com.itemsharing: DEBUG
    org.springframework.web: DEBUG

spring:
  application:
    name: zuul    