server:
  port: 8901

liquibase:
  contexts: local
  enabled: true

spring:
  application:
    name: auth
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      jadira:
        usertype:
          autoRegisterUserTypes: true

  datasource:
    url: jdbc:postgresql://localhost:59595/itemsharingdatabase
    username: "postgres"
    password: "root"
    driver-class-name: org.postgresql.Driver
    

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8901/user
      
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

